//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STM.Core.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\_ptm_preset_]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;ssh&quot;
        ///&quot;PortNumber&quot;=dword:00000016
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000000
        ///&quot;PingIntervalSecs&quot;=dword:00000000
        ///&quot;TCPNo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultPuttyProfile {
            get {
                return ResourceManager.GetString("DefaultPuttyProfile", resourceCulture);
            }
        }
    }
}
